config/routes.rb
Rails.application.routes.draw do

  root 'galleries#index'

  resources :galleries do
    member do
      put 'set_default', as: 'default_painting_on'
    end
    resources :paintings
  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base

  has_many :paintings

  validates :name, presence: true
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :gallery

  validates :name, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :set_gallery, only: [:show, :edit, :update, :destroy, :set_default]
  before_action :build_gallery, only: [:new, :create, :update]

  def index
    @galleries = Gallery.all
  end

  def new
  end

  def create
    if @gallery.save
      flash[:success] = "New gallery created."
      redirect_to @gallery
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @gallery.save
      flash[:success] = "Gallery was successfully updated."
      redirect_to @gallery
    else
      render 'new'
    end
  end

  def destroy
    @gallery.destroy
    redirect_to root_path, :notice => "#{@gallery.name} was deleted."
  end

  def set_default
    @gallery.default_painting = params[:painting_id]
    # flash[:success] = "Set as default painting for #{@gallery.name}"
    @gallery.save
    redirect_to :back, :notice => "Set as default painting for #{@gallery.name}"
  end

  private

  def set_gallery
    @gallery = Gallery.find(params[:id])
  end

  def build_gallery
    @gallery ||= Gallery.new
    @gallery.attributes = gallery_params
  end

  def gallery_params
    var = params[:gallery]
    var ? var.permit(:name) : {}
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_gallery
  before_action :set_painting, only: [:edit, :update, :destroy]

  def new
    build_painting
  end

  def create
    build_painting

    if @painting.save
      flash[:success] = "Painting was successfully saved."
      redirect_to @gallery
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    build_painting

    if @painting.save
      flash[:success] = "Painting was successfully updated."
      redirect_to @gallery
    else
      render 'edit'
    end
  end

  def destroy
    if @painting.destroy
      flash[:success] = "Painting was removed from #{@gallery.name}"
    end
    redirect_to :back
  end

  private

  def set_gallery
    @gallery = Gallery.find(params[:gallery_id])
  end

  def set_painting
    @painting ||= Painting.find(params[:id])
  end

  def build_painting
    @painting ||= @gallery.paintings.new
    @painting.attributes = painting_params
  end

  def painting_params
    var = params[:painting]
    var ? var.permit(:name, :image, :remote_image_url) : {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper

  def default_image(gallery)
    if gallery.default_painting
      Painting.find(gallery.default_painting).image_url(:thumb).to_s
    else
      gallery.paintings.first.image_url(:thumb).to_s
    end
  end
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/galleries/_form.html.erb
<%= render 'layouts/errors', obj: @gallery %>

<%= form_for @gallery do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, :autofocus => true %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/galleries/edit.html.erb
<h1>New Gallery</h1>

<%= render 'form' %>

app/views/galleries/index.html.erb
<div class="col-lg-12">
    <h1 class="page-header">Thumbnail Gallery</h1>
</div>

<% @galleries.each do |gallery| %>

  <div class="col-lg-3 col-md-4 col-xs-6 thumb">
      <%= link_to gallery_path(gallery), class: "thumbnail" do %>
        <% if gallery.paintings.count == 0 %>
          <img class="img-responsive" src="http://placehold.it/600x600" alt="">
        <% else %>
          <%= image_tag default_image(gallery) %>
        <% end %>
      <% end %>
      <div class="text-center">
        <p>
          <strong><%= gallery.name %>:</strong> <%= pluralize(gallery.paintings.count, "Painting") %><br>
        </p>
        <div class="btn-group">
          <%= link_to "edit", edit_gallery_path(gallery), class: "btn btn-sm btn-default" %>
          <%= link_to "remove", gallery_path(gallery), method: :delete, data: { confirm: "Associated paintings will be deleted as well.\n\nAre you sure?" }, class: "btn btn-sm btn-default" %>
        </div>
      </div>
  </div>

<% end %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render 'layouts/errors', obj: @gallery %>

<%= form_for @gallery do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/galleries/show.html.erb
<div class="col-lg-12">
  <h1 class="page-header"><%= @gallery.name %></h1>
</div>

<% @gallery.paintings.each do |painting| %>

  <div class="col-lg-3 col-md-4 col-xs-6 thumb">
    <div class="thumbnail <%= "default_painting" if @gallery.default_painting == painting.id %>">
      <%= link_to (image_tag painting.image_url(:thumb).to_s), default_painting_on_gallery_path(@gallery, painting_id: painting), method: :put %>
    </div>
    <%= painting.name %> |
    <%= link_to "edit", edit_gallery_painting_path(@gallery, painting) %> |
    <%= link_to "remove", gallery_painting_path(@gallery, painting), data: { confirm: "Are you sure?" }, method: :delete %>
  </div>

<% end %>

app/views/layouts/_errors.html.erb
  <% if obj.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(obj.errors.count, "error") %> prohibited this test from being saved:</h2>

      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Carrierwave File Uploads</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Carrierwave File Uploads</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><%= link_to "New Gallery", new_gallery_path %></li>

                    <% if params[:action] == "show" %>
                      <li><%= link_to "New Painting", new_gallery_painting_path(params[:id]) %></li>
                    <% end %>

                    <% if params[:controller] == "paintings" %>
                      <li><%= link_to @gallery.name, @gallery %></li>
                    <% end %>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">
          <% flash.each do |key, msg| %>
            <div class="alert alert-<%= key == "notice" ? "success" : key %>" role="alert"><%= msg %></div>
          <% end %>
        </div>

        <div class="row">
            <%= yield %>
        </div>

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                  <p>Rails App: Carrierwave File Uploads</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

</body>

</html>

app/views/paintings/_form.html.erb
<%= render 'layouts/errors', obj: @painting %>

<%= form_for [@gallery, @painting], html: { multipart: true } do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :remote_image_url, "or image URL:" %><br>
    <%= f.text_field :remote_image_url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/paintings/edit.html.erb
<h1>Edit <%= @painting.name %> on Gallery: <%= @gallery.name %></h1>

<%= render 'form' %>

app/views/paintings/new.html.erb
<h1>Add to Gallery: <%= @gallery.name %></h1>

<%= render 'form' %>